/-
Port of the Haskell test module `ExpressionParser`.
-/
import LanguageJavascriptTests.Utils

namespace Test.Language.Javascript

def testExpressionParser : List Test :=
  -- this
  [ shouldBe "this" (testExpr "this") "Right (JSAstExpression (JSLiteral 'this'))"
  -- regex
  , shouldBe "/blah/" (testExpr "/blah/") "Right (JSAstExpression (JSRegEx '/blah/'))"
  , shouldBe "/$/g" (testExpr "/$/g") "Right (JSAstExpression (JSRegEx '/$/g'))"
  , shouldBe "/\\n/g" (testExpr "/\\n/g") "Right (JSAstExpression (JSRegEx '/\\n/g'))"
  , shouldBe "/(\\/)/" (testExpr "/(\\/)/") "Right (JSAstExpression (JSRegEx '/(\\/)/'))"
  , shouldBe "/a[/]b/" (testExpr "/a[/]b/") "Right (JSAstExpression (JSRegEx '/a[/]b/'))"
  , shouldBe "/[/\\]/" (testExpr "/[/\\]/") "Right (JSAstExpression (JSRegEx '/[/\\]/'))"
  , shouldBe "/(\\/|\\)/" (testExpr "/(\\/|\\)/") "Right (JSAstExpression (JSRegEx '/(\\/|\\)/'))"
  , shouldBe "/a\\[|\\]$/g" (testExpr "/a\\[|\\]$/g") "Right (JSAstExpression (JSRegEx '/a\\[|\\]$/g'))"
  , shouldBe "/[(){}\\[\\]]/g" (testExpr "/[(){}\\[\\]]/g") "Right (JSAstExpression (JSRegEx '/[(){}\\[\\]]/g'))"
  , shouldBe "/^\"(?:\\.|[^\"])*\"|^'(?:[^']|\\.)*'/" (testExpr "/^\"(?:\\.|[^\"])*\"|^'(?:[^']|\\.)*'/") "Right (JSAstExpression (JSRegEx '/^\"(?:\\.|[^\"])*\"|^'(?:[^']|\\.)*'/'))"
  -- identifier
  , shouldBe "_$" (testExpr "_$") "Right (JSAstExpression (JSIdentifier '_$'))"
  , shouldBe "this_" (testExpr "this_") "Right (JSAstExpression (JSIdentifier 'this_'))"
  -- array literal
  , shouldBe "[]" (testExpr "[]") "Right (JSAstExpression (JSArrayLiteral []))"
  , shouldBe "[,]" (testExpr "[,]") "Right (JSAstExpression (JSArrayLiteral [JSComma]))"
  , shouldBe "[,,]" (testExpr "[,,]") "Right (JSAstExpression (JSArrayLiteral [JSComma,JSComma]))"
  , shouldBe "[,,x]" (testExpr "[,,x]") "Right (JSAstExpression (JSArrayLiteral [JSComma,JSComma,JSIdentifier 'x']))"
  , shouldBe "[,,x]" (testExpr "[,,x]") "Right (JSAstExpression (JSArrayLiteral [JSComma,JSComma,JSIdentifier 'x']))"
  , shouldBe "[,x,,x]" (testExpr "[,x,,x]") "Right (JSAstExpression (JSArrayLiteral [JSComma,JSIdentifier 'x',JSComma,JSComma,JSIdentifier 'x']))"
  , shouldBe "[x]" (testExpr "[x]") "Right (JSAstExpression (JSArrayLiteral [JSIdentifier 'x']))"
  , shouldBe "[x,]" (testExpr "[x,]") "Right (JSAstExpression (JSArrayLiteral [JSIdentifier 'x',JSComma]))"
  , shouldBe "[,,,]" (testExpr "[,,,]") "Right (JSAstExpression (JSArrayLiteral [JSComma,JSComma,JSComma]))"
  , shouldBe "[a,,]" (testExpr "[a,,]") "Right (JSAstExpression (JSArrayLiteral [JSIdentifier 'a',JSComma,JSComma]))"
  -- operator precedence
  , shouldBe "2+3*4+5" (testExpr "2+3*4+5") "Right (JSAstExpression (JSExpressionBinary ('+',JSExpressionBinary ('+',JSDecimal '2',JSExpressionBinary ('*',JSDecimal '3',JSDecimal '4')),JSDecimal '5')))"
  -- parentheses
  , shouldBe "(56)" (testExpr "(56)") "Right (JSAstExpression (JSExpressionParen (JSDecimal '56')))"
  -- string concatenation
  , shouldBe "'ab' + 'bc'" (testExpr "'ab' + 'bc'") "Right (JSAstExpression (JSExpressionBinary ('+',JSStringLiteral 'ab',JSStringLiteral 'bc')))"
  , shouldBe "'bc' + \"cd\"" (testExpr "'bc' + \"cd\"") "Right (JSAstExpression (JSExpressionBinary ('+',JSStringLiteral 'bc',JSStringLiteral \"cd\")))"
  -- object literal
  , shouldBe "{}" (testExpr "{}") "Right (JSAstExpression (JSObjectLiteral []))"
  , shouldBe "{x:1}" (testExpr "{x:1}") "Right (JSAstExpression (JSObjectLiteral [JSPropertyNameandValue (JSIdentifier 'x') [JSDecimal '1']]))"
  , shouldBe "{x:1,y:2}" (testExpr "{x:1,y:2}") "Right (JSAstExpression (JSObjectLiteral [JSPropertyNameandValue (JSIdentifier 'x') [JSDecimal '1'],JSPropertyNameandValue (JSIdentifier 'y') [JSDecimal '2']]))"
  , shouldBe "{x:1,}" (testExpr "{x:1,}") "Right (JSAstExpression (JSObjectLiteral [JSPropertyNameandValue (JSIdentifier 'x') [JSDecimal '1'],JSComma]))"
  , shouldBe "{yield:1}" (testExpr "{yield:1}") "Right (JSAstExpression (JSObjectLiteral [JSPropertyNameandValue (JSIdentifier 'yield') [JSDecimal '1']]))"
  , shouldBe "{x}" (testExpr "{x}") "Right (JSAstExpression (JSObjectLiteral [JSPropertyIdentRef 'x']))"
  , shouldBe "{x,}" (testExpr "{x,}") "Right (JSAstExpression (JSObjectLiteral [JSPropertyIdentRef 'x',JSComma]))"
  , shouldBe "{set x([a,b]=y) {this.a=a;this.b=b}}" (testExpr "{set x([a,b]=y) {this.a=a;this.b=b}}") "Right (JSAstExpression (JSObjectLiteral [JSPropertyAccessor JSAccessorSet (JSIdentifier 'x') (JSOpAssign ('=',JSArrayLiteral [JSIdentifier 'a',JSComma,JSIdentifier 'b'],JSIdentifier 'y')) (JSBlock [JSOpAssign ('=',JSMemberDot (JSLiteral 'this',JSIdentifier 'a'),JSIdentifier 'a'),JSSemicolon,JSOpAssign ('=',JSMemberDot (JSLiteral 'this',JSIdentifier 'b'),JSIdentifier 'b')])]))"
  , shouldBe "a={if:1,interface:2}" (testExpr "a={if:1,interface:2}") "Right (JSAstExpression (JSOpAssign ('=',JSIdentifier 'a',JSObjectLiteral [JSPropertyNameandValue (JSIdentifier 'if') [JSDecimal '1'],JSPropertyNameandValue (JSIdentifier 'interface') [JSDecimal '2']])))"
  , shouldBe "a={\n  values: 7,\n}\n" (testExpr "a={\n  values: 7,\n}\n") "Right (JSAstExpression (JSOpAssign ('=',JSIdentifier 'a',JSObjectLiteral [JSPropertyNameandValue (JSIdentifier 'values') [JSDecimal '7'],JSComma])))"
  , shouldBe "x={get foo() {return 1},set foo(a) {x=a}}" (testExpr "x={get foo() {return 1},set foo(a) {x=a}}") "Right (JSAstExpression (JSOpAssign ('=',JSIdentifier 'x',JSObjectLiteral [JSPropertyAccessor JSAccessorGet (JSIdentifier 'foo') () (JSBlock [JSReturn JSDecimal '1' ]),JSPropertyAccessor JSAccessorSet (JSIdentifier 'foo') (JSIdentifier 'a') (JSBlock [JSOpAssign ('=',JSIdentifier 'x',JSIdentifier 'a')])])))"
  , shouldBe "{evaluate:evaluate,load:function load(s){if(x)return s;1}}" (testExpr "{evaluate:evaluate,load:function load(s){if(x)return s;1}}") "Right (JSAstExpression (JSObjectLiteral [JSPropertyNameandValue (JSIdentifier 'evaluate') [JSIdentifier 'evaluate'],JSPropertyNameandValue (JSIdentifier 'load') [JSFunctionExpression 'load' (JSIdentifier 's') (JSBlock [JSIf (JSIdentifier 'x') (JSReturn JSIdentifier 's' JSSemicolon),JSDecimal '1'])]]))"
  , shouldBe "obj = { name : 'A', 'str' : 'B', 123 : 'C', }" (testExpr "obj = { name : 'A', 'str' : 'B', 123 : 'C', }") "Right (JSAstExpression (JSOpAssign ('=',JSIdentifier 'obj',JSObjectLiteral [JSPropertyNameandValue (JSIdentifier 'name') [JSStringLiteral 'A'],JSPropertyNameandValue (JSIdentifier ''str'') [JSStringLiteral 'B'],JSPropertyNameandValue (JSIdentifier '123') [JSStringLiteral 'C'],JSComma])))"
  , shouldBe "{[x]:1}" (testExpr "{[x]:1}") "Right (JSAstExpression (JSObjectLiteral [JSPropertyNameandValue (JSPropertyComputed (JSIdentifier 'x')) [JSDecimal '1']]))"
  , shouldBe "{ a(x,y) {}, 'blah blah'() {} }" (testExpr "{ a(x,y) {}, 'blah blah'() {} }") "Right (JSAstExpression (JSObjectLiteral [JSMethodDefinition (JSIdentifier 'a') (JSIdentifier 'x',JSIdentifier 'y') (JSBlock []),JSMethodDefinition (JSIdentifier ''blah blah'') () (JSBlock [])]))"
  , shouldBe "{[x]() {}}" (testExpr "{[x]() {}}") "Right (JSAstExpression (JSObjectLiteral [JSMethodDefinition (JSPropertyComputed (JSIdentifier 'x')) () (JSBlock [])]))"
  , shouldBe "{*a(x,y) {yield y;}}" (testExpr "{*a(x,y) {yield y;}}") "Right (JSAstExpression (JSObjectLiteral [JSGeneratorMethodDefinition (JSIdentifier 'a') (JSIdentifier 'x',JSIdentifier 'y') (JSBlock [JSYieldExpression (JSIdentifier 'y'),JSSemicolon])]))"
  , shouldBe "{*[x]({y},...z) {}}" (testExpr "{*[x]({y},...z) {}}") "Right (JSAstExpression (JSObjectLiteral [JSGeneratorMethodDefinition (JSPropertyComputed (JSIdentifier 'x')) (JSObjectLiteral [JSPropertyIdentRef 'y'],JSSpreadExpression (JSIdentifier 'z')) (JSBlock [])]))"
  -- unary expression
  , shouldBe "delete y" (testExpr "delete y") "Right (JSAstExpression (JSUnaryExpression ('delete',JSIdentifier 'y')))"
  , shouldBe "void y" (testExpr "void y") "Right (JSAstExpression (JSUnaryExpression ('void',JSIdentifier 'y')))"
  , shouldBe "typeof y" (testExpr "typeof y") "Right (JSAstExpression (JSUnaryExpression ('typeof',JSIdentifier 'y')))"
  , shouldBe "++y" (testExpr "++y") "Right (JSAstExpression (JSUnaryExpression ('++',JSIdentifier 'y')))"
  , shouldBe "--y" (testExpr "--y") "Right (JSAstExpression (JSUnaryExpression ('--',JSIdentifier 'y')))"
  , shouldBe "+y" (testExpr "+y") "Right (JSAstExpression (JSUnaryExpression ('+',JSIdentifier 'y')))"
  , shouldBe "-y" (testExpr "-y") "Right (JSAstExpression (JSUnaryExpression ('-',JSIdentifier 'y')))"
  , shouldBe "~y" (testExpr "~y") "Right (JSAstExpression (JSUnaryExpression ('~',JSIdentifier 'y')))"
  , shouldBe "!y" (testExpr "!y") "Right (JSAstExpression (JSUnaryExpression ('!',JSIdentifier 'y')))"
  , shouldBe "y++" (testExpr "y++") "Right (JSAstExpression (JSExpressionPostfix ('++',JSIdentifier 'y')))"
  , shouldBe "y--" (testExpr "y--") "Right (JSAstExpression (JSExpressionPostfix ('--',JSIdentifier 'y')))"
  , shouldBe "...y" (testExpr "...y") "Right (JSAstExpression (JSSpreadExpression (JSIdentifier 'y')))"
  -- new expression
  , shouldBe "new x()" (testExpr "new x()") "Right (JSAstExpression (JSMemberNew (JSIdentifier 'x',JSArguments ())))"
  , shouldBe "new x.y" (testExpr "new x.y") "Right (JSAstExpression (JSNewExpression JSMemberDot (JSIdentifier 'x',JSIdentifier 'y')))"
  -- binary expression
  , shouldBe "x||y" (testExpr "x||y") "Right (JSAstExpression (JSExpressionBinary ('||',JSIdentifier 'x',JSIdentifier 'y')))"
  , shouldBe "x&&y" (testExpr "x&&y") "Right (JSAstExpression (JSExpressionBinary ('&&',JSIdentifier 'x',JSIdentifier 'y')))"
  , shouldBe "x|y" (testExpr "x|y") "Right (JSAstExpression (JSExpressionBinary ('|',JSIdentifier 'x',JSIdentifier 'y')))"
  , shouldBe "x^y" (testExpr "x^y") "Right (JSAstExpression (JSExpressionBinary ('^',JSIdentifier 'x',JSIdentifier 'y')))"
  , shouldBe "x&y" (testExpr "x&y") "Right (JSAstExpression (JSExpressionBinary ('&',JSIdentifier 'x',JSIdentifier 'y')))"
  , shouldBe "x==y" (testExpr "x==y") "Right (JSAstExpression (JSExpressionBinary ('==',JSIdentifier 'x',JSIdentifier 'y')))"
  , shouldBe "x!=y" (testExpr "x!=y") "Right (JSAstExpression (JSExpressionBinary ('!=',JSIdentifier 'x',JSIdentifier 'y')))"
  , shouldBe "x===y" (testExpr "x===y") "Right (JSAstExpression (JSExpressionBinary ('===',JSIdentifier 'x',JSIdentifier 'y')))"
  , shouldBe "x!==y" (testExpr "x!==y") "Right (JSAstExpression (JSExpressionBinary ('!==',JSIdentifier 'x',JSIdentifier 'y')))"
  , shouldBe "x<y" (testExpr "x<y") "Right (JSAstExpression (JSExpressionBinary ('<',JSIdentifier 'x',JSIdentifier 'y')))"
  , shouldBe "x>y" (testExpr "x>y") "Right (JSAstExpression (JSExpressionBinary ('>',JSIdentifier 'x',JSIdentifier 'y')))"
  , shouldBe "x<=y" (testExpr "x<=y") "Right (JSAstExpression (JSExpressionBinary ('<=',JSIdentifier 'x',JSIdentifier 'y')))"
  , shouldBe "x>=y" (testExpr "x>=y") "Right (JSAstExpression (JSExpressionBinary ('>=',JSIdentifier 'x',JSIdentifier 'y')))"
  , shouldBe "x<<y" (testExpr "x<<y") "Right (JSAstExpression (JSExpressionBinary ('<<',JSIdentifier 'x',JSIdentifier 'y')))"
  , shouldBe "x>>y" (testExpr "x>>y") "Right (JSAstExpression (JSExpressionBinary ('>>',JSIdentifier 'x',JSIdentifier 'y')))"
  , shouldBe "x>>>y" (testExpr "x>>>y") "Right (JSAstExpression (JSExpressionBinary ('>>>',JSIdentifier 'x',JSIdentifier 'y')))"
  , shouldBe "x+y" (testExpr "x+y") "Right (JSAstExpression (JSExpressionBinary ('+',JSIdentifier 'x',JSIdentifier 'y')))"
  , shouldBe "x-y" (testExpr "x-y") "Right (JSAstExpression (JSExpressionBinary ('-',JSIdentifier 'x',JSIdentifier 'y')))"
  , shouldBe "x*y" (testExpr "x*y") "Right (JSAstExpression (JSExpressionBinary ('*',JSIdentifier 'x',JSIdentifier 'y')))"
  , shouldBe "x/y" (testExpr "x/y") "Right (JSAstExpression (JSExpressionBinary ('/',JSIdentifier 'x',JSIdentifier 'y')))"
  , shouldBe "x%y" (testExpr "x%y") "Right (JSAstExpression (JSExpressionBinary ('%',JSIdentifier 'x',JSIdentifier 'y')))"
  , shouldBe "x instanceof y" (testExpr "x instanceof y") "Right (JSAstExpression (JSExpressionBinary ('instanceof',JSIdentifier 'x',JSIdentifier 'y')))"
  -- assign expression
  , shouldBe "x=1" (testExpr "x=1") "Right (JSAstExpression (JSOpAssign ('=',JSIdentifier 'x',JSDecimal '1')))"
  , shouldBe "x*=1" (testExpr "x*=1") "Right (JSAstExpression (JSOpAssign ('*=',JSIdentifier 'x',JSDecimal '1')))"
  , shouldBe "x/=1" (testExpr "x/=1") "Right (JSAstExpression (JSOpAssign ('/=',JSIdentifier 'x',JSDecimal '1')))"
  , shouldBe "x%=1" (testExpr "x%=1") "Right (JSAstExpression (JSOpAssign ('%=',JSIdentifier 'x',JSDecimal '1')))"
  , shouldBe "x+=1" (testExpr "x+=1") "Right (JSAstExpression (JSOpAssign ('+=',JSIdentifier 'x',JSDecimal '1')))"
  , shouldBe "x-=1" (testExpr "x-=1") "Right (JSAstExpression (JSOpAssign ('-=',JSIdentifier 'x',JSDecimal '1')))"
  , shouldBe "x<<=1" (testExpr "x<<=1") "Right (JSAstExpression (JSOpAssign ('<<=',JSIdentifier 'x',JSDecimal '1')))"
  , shouldBe "x>>=1" (testExpr "x>>=1") "Right (JSAstExpression (JSOpAssign ('>>=',JSIdentifier 'x',JSDecimal '1')))"
  , shouldBe "x>>>=1" (testExpr "x>>>=1") "Right (JSAstExpression (JSOpAssign ('>>>=',JSIdentifier 'x',JSDecimal '1')))"
  , shouldBe "x&=1" (testExpr "x&=1") "Right (JSAstExpression (JSOpAssign ('&=',JSIdentifier 'x',JSDecimal '1')))"
  , shouldBe "x^=1" (testExpr "x^=1") "Right (JSAstExpression (JSOpAssign ('^=',JSIdentifier 'x',JSDecimal '1')))"
  , shouldBe "x|=1" (testExpr "x|=1") "Right (JSAstExpression (JSOpAssign ('|=',JSIdentifier 'x',JSDecimal '1')))"
  -- function expression
  , shouldBe "function(){}" (testExpr "function(){}") "Right (JSAstExpression (JSFunctionExpression '' () (JSBlock [])))"
  , shouldBe "function(a){}" (testExpr "function(a){}") "Right (JSAstExpression (JSFunctionExpression '' (JSIdentifier 'a') (JSBlock [])))"
  , shouldBe "function(a,b){}" (testExpr "function(a,b){}") "Right (JSAstExpression (JSFunctionExpression '' (JSIdentifier 'a',JSIdentifier 'b') (JSBlock [])))"
  , shouldBe "function(...a){}" (testExpr "function(...a){}") "Right (JSAstExpression (JSFunctionExpression '' (JSSpreadExpression (JSIdentifier 'a')) (JSBlock [])))"
  , shouldBe "function(a=1){}" (testExpr "function(a=1){}") "Right (JSAstExpression (JSFunctionExpression '' (JSOpAssign ('=',JSIdentifier 'a',JSDecimal '1')) (JSBlock [])))"
  , shouldBe "function([a,b]){}" (testExpr "function([a,b]){}") "Right (JSAstExpression (JSFunctionExpression '' (JSArrayLiteral [JSIdentifier 'a',JSComma,JSIdentifier 'b']) (JSBlock [])))"
  , shouldBe "function([a,...b]){}" (testExpr "function([a,...b]){}") "Right (JSAstExpression (JSFunctionExpression '' (JSArrayLiteral [JSIdentifier 'a',JSComma,JSSpreadExpression (JSIdentifier 'b')]) (JSBlock [])))"
  , shouldBe "function({a,b}){}" (testExpr "function({a,b}){}") "Right (JSAstExpression (JSFunctionExpression '' (JSObjectLiteral [JSPropertyIdentRef 'a',JSPropertyIdentRef 'b']) (JSBlock [])))"
  , shouldBe "a => {}" (testExpr "a => {}") "Right (JSAstExpression (JSArrowExpression (JSIdentifier 'a') => JSStatementBlock []))"
  , shouldBe "(a) => { a + 2 }" (testExpr "(a) => { a + 2 }") "Right (JSAstExpression (JSArrowExpression ((JSIdentifier 'a')) => JSStatementBlock [JSExpressionBinary ('+',JSIdentifier 'a',JSDecimal '2')]))"
  , shouldBe "(a, b) => {}" (testExpr "(a, b) => {}") "Right (JSAstExpression (JSArrowExpression ((JSIdentifier 'a',JSIdentifier 'b')) => JSStatementBlock []))"
  , shouldBe "(a, b) => a + b" (testExpr "(a, b) => a + b") "Right (JSAstExpression (JSArrowExpression ((JSIdentifier 'a',JSIdentifier 'b')) => JSExpressionBinary ('+',JSIdentifier 'a',JSIdentifier 'b')))"
  , shouldBe "() => { 42 }" (testExpr "() => { 42 }") "Right (JSAstExpression (JSArrowExpression (()) => JSStatementBlock [JSDecimal '42']))"
  , shouldBe "(a, ...b) => b" (testExpr "(a, ...b) => b") "Right (JSAstExpression (JSArrowExpression ((JSIdentifier 'a',JSSpreadExpression (JSIdentifier 'b'))) => JSIdentifier 'b'))"
  , shouldBe "(a,b=1) => a + b" (testExpr "(a,b=1) => a + b") "Right (JSAstExpression (JSArrowExpression ((JSIdentifier 'a',JSOpAssign ('=',JSIdentifier 'b',JSDecimal '1'))) => JSExpressionBinary ('+',JSIdentifier 'a',JSIdentifier 'b')))"
  , shouldBe "([a,b]) => a + b" (testExpr "([a,b]) => a + b") "Right (JSAstExpression (JSArrowExpression ((JSArrayLiteral [JSIdentifier 'a',JSComma,JSIdentifier 'b'])) => JSExpressionBinary ('+',JSIdentifier 'a',JSIdentifier 'b')))"
  -- generator expression
  , shouldBe "function*(){}" (testExpr "function*(){}") "Right (JSAstExpression (JSGeneratorExpression '' () (JSBlock [])))"
  , shouldBe "function*(a){}" (testExpr "function*(a){}") "Right (JSAstExpression (JSGeneratorExpression '' (JSIdentifier 'a') (JSBlock [])))"
  , shouldBe "function*(a,b){}" (testExpr "function*(a,b){}") "Right (JSAstExpression (JSGeneratorExpression '' (JSIdentifier 'a',JSIdentifier 'b') (JSBlock [])))"
  , shouldBe "function*(a,...b){}" (testExpr "function*(a,...b){}") "Right (JSAstExpression (JSGeneratorExpression '' (JSIdentifier 'a',JSSpreadExpression (JSIdentifier 'b')) (JSBlock [])))"
  , shouldBe "function*f(){}" (testExpr "function*f(){}") "Right (JSAstExpression (JSGeneratorExpression 'f' () (JSBlock [])))"
  , shouldBe "function*f(a){}" (testExpr "function*f(a){}") "Right (JSAstExpression (JSGeneratorExpression 'f' (JSIdentifier 'a') (JSBlock [])))"
  , shouldBe "function*f(a,b){}" (testExpr "function*f(a,b){}") "Right (JSAstExpression (JSGeneratorExpression 'f' (JSIdentifier 'a',JSIdentifier 'b') (JSBlock [])))"
  , shouldBe "function*f(a,...b){}" (testExpr "function*f(a,...b){}") "Right (JSAstExpression (JSGeneratorExpression 'f' (JSIdentifier 'a',JSSpreadExpression (JSIdentifier 'b')) (JSBlock [])))"
  -- member expression
  , shouldBe "x[y]" (testExpr "x[y]") "Right (JSAstExpression (JSMemberSquare (JSIdentifier 'x',JSIdentifier 'y')))"
  , shouldBe "x[y][z]" (testExpr "x[y][z]") "Right (JSAstExpression (JSMemberSquare (JSMemberSquare (JSIdentifier 'x',JSIdentifier 'y'),JSIdentifier 'z')))"
  , shouldBe "x.y" (testExpr "x.y") "Right (JSAstExpression (JSMemberDot (JSIdentifier 'x',JSIdentifier 'y')))"
  , shouldBe "x.y.z" (testExpr "x.y.z") "Right (JSAstExpression (JSMemberDot (JSMemberDot (JSIdentifier 'x',JSIdentifier 'y'),JSIdentifier 'z')))"
  -- call expression
  , shouldBe "x()" (testExpr "x()") "Right (JSAstExpression (JSMemberExpression (JSIdentifier 'x',JSArguments ())))"
  , shouldBe "x()()" (testExpr "x()()") "Right (JSAstExpression (JSCallExpression (JSMemberExpression (JSIdentifier 'x',JSArguments ()),JSArguments ())))"
  , shouldBe "x()[4]" (testExpr "x()[4]") "Right (JSAstExpression (JSCallExpressionSquare (JSMemberExpression (JSIdentifier 'x',JSArguments ()),JSDecimal '4')))"
  , shouldBe "x().x" (testExpr "x().x") "Right (JSAstExpression (JSCallExpressionDot (JSMemberExpression (JSIdentifier 'x',JSArguments ()),JSIdentifier 'x')))"
  , shouldBe "x(a,b=2).x" (testExpr "x(a,b=2).x") "Right (JSAstExpression (JSCallExpressionDot (JSMemberExpression (JSIdentifier 'x',JSArguments (JSIdentifier 'a',JSOpAssign ('=',JSIdentifier 'b',JSDecimal '2'))),JSIdentifier 'x')))"
  , shouldBe "foo (56.8379100, 60.5806664)" (testExpr "foo (56.8379100, 60.5806664)") "Right (JSAstExpression (JSMemberExpression (JSIdentifier 'foo',JSArguments (JSDecimal '56.8379100',JSDecimal '60.5806664'))))"
  -- spread expression
  , shouldBe "... x" (testExpr "... x") "Right (JSAstExpression (JSSpreadExpression (JSIdentifier 'x')))"
  -- template literal
  , shouldBe "``" (testExpr "``") "Right (JSAstExpression (JSTemplateLiteral ((),'``',[])))"
  , shouldBe "`$`" (testExpr "`$`") "Right (JSAstExpression (JSTemplateLiteral ((),'`$`',[])))"
  , shouldBe "`$\\n`" (testExpr "`$\\n`") "Right (JSAstExpression (JSTemplateLiteral ((),'`$\\n`',[])))"
  , shouldBe "`\\${x}`" (testExpr "`\\${x}`") "Right (JSAstExpression (JSTemplateLiteral ((),'`\\${x}`',[])))"
  , shouldBe "`$ {x}`" (testExpr "`$ {x}`") "Right (JSAstExpression (JSTemplateLiteral ((),'`$ {x}`',[])))"
  , shouldBe "`\n\n`" (testExpr "`\n\n`") "Right (JSAstExpression (JSTemplateLiteral ((),'`\n\n`',[])))"
  , shouldBe "`${x+y} ${z}`" (testExpr "`${x+y} ${z}`") "Right (JSAstExpression (JSTemplateLiteral ((),'`${',[(JSExpressionBinary ('+',JSIdentifier 'x',JSIdentifier 'y'),'} ${'),(JSIdentifier 'z','}`')])))"
  , shouldBe "`<${x} ${y}>`" (testExpr "`<${x} ${y}>`") "Right (JSAstExpression (JSTemplateLiteral ((),'`<${',[(JSIdentifier 'x','} ${'),(JSIdentifier 'y','}>`')])))"
  , shouldBe "tag `xyz`" (testExpr "tag `xyz`") "Right (JSAstExpression (JSTemplateLiteral ((JSIdentifier 'tag'),'`xyz`',[])))"
  , shouldBe "tag()`xyz`" (testExpr "tag()`xyz`") "Right (JSAstExpression (JSTemplateLiteral ((JSMemberExpression (JSIdentifier 'tag',JSArguments ())),'`xyz`',[])))"
  -- yield
  , shouldBe "yield" (testExpr "yield") "Right (JSAstExpression (JSYieldExpression ()))"
  , shouldBe "yield a + b" (testExpr "yield a + b") "Right (JSAstExpression (JSYieldExpression (JSExpressionBinary ('+',JSIdentifier 'a',JSIdentifier 'b'))))"
  , shouldBe "yield* g()" (testExpr "yield* g()") "Right (JSAstExpression (JSYieldFromExpression (JSMemberExpression (JSIdentifier 'g',JSArguments ()))))"
  -- class expression
  , shouldBe "class Foo extends Bar { a(x,y) {} *b() {} }" (testExpr "class Foo extends Bar { a(x,y) {} *b() {} }") "Right (JSAstExpression (JSClassExpression 'Foo' (JSIdentifier 'Bar') [JSMethodDefinition (JSIdentifier 'a') (JSIdentifier 'x',JSIdentifier 'y') (JSBlock []),JSGeneratorMethodDefinition (JSIdentifier 'b') () (JSBlock [])]))"
  , shouldBe "class { static get [a]() {}; }" (testExpr "class { static get [a]() {}; }") "Right (JSAstExpression (JSClassExpression '' () [JSClassStaticMethod (JSPropertyAccessor JSAccessorGet (JSPropertyComputed (JSIdentifier 'a')) () (JSBlock [])),JSClassSemi]))"
  , shouldBe "class Foo extends Bar { a(x,y) { super(x); } }" (testExpr "class Foo extends Bar { a(x,y) { super(x); } }") "Right (JSAstExpression (JSClassExpression 'Foo' (JSIdentifier 'Bar') [JSMethodDefinition (JSIdentifier 'a') (JSIdentifier 'x',JSIdentifier 'y') (JSBlock [JSCallExpression (JSLiteral 'super',JSArguments (JSIdentifier 'x')),JSSemicolon])]))"
  ]

#guard allPass testExpressionParser

end Test.Language.Javascript
